FROM gradle:jdk19-jammy AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN ./gradlew build --no-daemon

# FROM node:16 as node_serverless
# WORKDIR /home/serverless
#
# RUN npm install -g serverless
# RUN npm install --save-dev serverless-localstack

FROM eclipse-temurin:19

EXPOSE 9000

RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/app.jar
COPY --from=build /home/gradle/src/build/distributions/*.zip ./build/distributions/event-service-java.zip
COPY ./serverless.yml ./serverless.yml

RUN apt-get update \
    && apt-get install nodejs npm --assume-yes \
    && npm install -g serverless serverless-localstack


CMD ["/bin/bash", "-c", "npx sls deploy --stage=local;java -XX:+CrashOnOutOfMemoryError -Xms256m -Xmx3072m -jar /app/app.jar"]
#ENTRYPOINT ["java", "-Xms256m", "-Xmx2048m", "-jar", "/app/app.jar"]
